workflows:
  my-workflow:                   # workflow ID
    name: Web workflow       # workflow name displayed in Codemagic UI
    instance_type: mac_mini_m1   # machine instance type
    max_build_duration: 60       # build duration in minutes (min 1, max 120)
    environment:
      groups:
        - firebase_credentials
      flutter: stable
    cache:
      cache_paths:
        - ~/.gradle/caches
    triggering:
      events: # List the events that trigger builds
        - push
    scripts:
      - echo "Testing Flutter app"
      - name: Flutter test
        script: flutter test
        ignore_failure: false
      - name: Packages Get
        script: flutter pub get
      - name: Build Web
        script: |
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*
      - name: Publish to Firebase Hosting
        script: |
         firebase deploy --token "$FIREBASE_TOKEN"

    artifacts:
      - build/web.zip
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - alabivictor015@gmail.com
        notify:
          success: true
          failure: true
      scripts:
        - echo 'Post-publish script'